### ISSUE TITLE
Lage oppgave-siden

### ISSUE THREAD

**Issue by boyebn** [IT2810/it2810-webutvikling-h17-prosjekt-3-group-7-web#21]
Se #5

**Comment by siljr** [comment]
Jeg har ikonene du trenger, bare spør! :D

**Comment by siljr** [comment]
[Alle bildene du trenger.zip](https://github.com/IT2810/it2810-webutvikling-h17-prosjekt-3-group-7/files/1373618/Archive.zip)

**Comment by siddiseh** [comment]
Branch: [feature/create-task-page](https://github.com/IT2810/it2810-webutvikling-h17-prosjekt-3-group-7/tree/feature/create-task-page)
