### ISSUE TITLE
Gjøre det mulig å opprette en ny avtale

### ISSUE THREAD

**Issue by boyebn** [IT2810/it2810-webutvikling-h17-prosjekt-3-group-7-web#22]
Se #5

**Comment by siljr** [comment]
Jeg har ikonene du trenger, bare spør! :D

**Comment by afriestad** [comment]
Branch: [feature/create-appointment-page](https://github.com/IT2810/it2810-webutvikling-h17-prosjekt-3-group-7-web/tree/feature/create-appointment-page)
