### ISSUE TITLE
Designe en løsning

### ISSUE THREAD

**Issue by afriestad** [IT2810/it2810-webutvikling-h17-prosjekt-3-group-7-web#5]
Fra oppgaveteksten:

> Denne oppgaven er to-delt- Først skal dere lage en webapplikasjon i React og deretter skal dere lage en tilsvarende app for mobil med React Native. Temaet for appen er "personal information manager" - en applikasjon som holder styr på avtaler, totater, varslinger, todo's etc. Vi har fokus på frontend og skal lagre data lokalt på maskinen/enheten.
>
>a) Personal Information Manager implementer med React
>
>Arbeidskrav:
>
>Design og implementer en Personal Information Manager med React javascript-biblioteket. Det er gruppa som bestemmer desing, innhold og funksjonalitet i applikasjonen
Grensesnittet skal være dynamisk - dvs. du skal kunne legge til nye elementer som kalendre i en tab, menyinnslag etc.
Tilstand lagres med HTML local storage, slik at du kan hente frem ditt oppsett, avtaler etc. Vi lager ingen backend-løsning.
Det er helt greit å supplere med andre bibliotek der det er hensiktsmessig (f.eks. til ui-komponenter).
Evaluering:
>
>Prosjektet skal løses innenfor den tidsrammen som er bestemt, det er opp til gruppene å lage en løsning innefor denne rammen. 
I evalueringen legges det vekt på godt desing, hvor avansert løsningen er, profesjonell kode, at du viser god bruk av React og at løsningen er testet.
>
>b) Personal Information Manager implementert med React Native
>
>Arbeidskrav:
>
>Design og implementer samme applikasjon med React Native (for Android/ios).
Gjør de tilpasninger som er nødvendig, men gjenbruk mest mulig kode.
Evaluering:
>
>Prosjektet skal løses innenfor den tidsrammen som er bestemt, det er opp til gruppene å lage en løsning innefor denne rammen. 
Evalueringen baseres på kodekvalitet og at løsningen virker, dvs at du har klart å overføre ide og kode fra web-applikasjonen
>
>Dette er en rimelig løst definert oppgave som er definert for å gi dere opplæring i HTML local state, React og React Native.

Ser for meg at vi i denne oppgaven unngår å bruke noe så komplekst som en kalender, men at vi heller holder oss til lister. Er det hensiktsmessig å bruke Redux (eller forsåvidt [Pockito](https://github.com/arnemahl/pockito)) og lagre hele storen som JSON i local storage?

Kan også tenkes at denne issuen bør deles inn i flere mindre; e.g. React, React Native, Design. Uansett bør vi diskutere til vi er på samme spor før vi begynner på løsningen :)

**Comment by siljr** [comment]
https://sketch.cloud/s/g0YEr
